my_string = (input("Какой сегодня день недели?"))
my_string = (input("Какой сегодня день недели?".upper ()))
input("Какой сегодня день недели?".upper ().lower ())
my_string = (input("Какой сегодня день недели?".replace(" ", "")))
my_string = (input("Какой сегодня день недели?"[0]))
my_string = (input("Какой сегодня день недели?"[-1]))